# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_photo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photolike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('is_liked', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo'),
        ),
    ]
